server:
  port: ${port:7070}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_test
    username: root
    password: root
  application:
    name: user-service

mybatis:
  type-aliases-package: com.ericsson.user.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${port0:80}/eureka,http://localhost:${port1:81}/eureka,http://localhost:${port2:82}/eureka

  instance:
    prefer-ip-address: true
    ip-address: 10.5.6.18
    #续约间隔,默认30s
    lease-renewal-interval-in-seconds: 5
    #服务失效时间,默认90s
    lease-expiration-duration-in-seconds: 5