server:
  port: 10010

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #路由id, 可以任意
        - id: user-service-route
          # 代理的服务地址
          # 动态路由.  lb表示从eureka中获取具体服务. lb之后编写的服务名必须是在eureka注册中心中注册的服务
          uri: lb://user-service
          #路由断言,可以匹配映射路径
          predicates:
#            - Path=/user/**
#            - Path=/**
            - Path=/api/user/**
          filters:
            #添加请求路径的前缀
#            - PrefixPath=/user
            # 1表示过滤一个路径, 2表示过滤两个路径, 一次类推
            - StripPrefix=1
            - MyParam=name
      # 默认过滤器，对所有路由都生效
      default-filters:
        - AddResponseHeader=X-Response-Foo,Bar
        - AddResponseHeader=User-Name,Luwasah
      globalcors:
        corsConfigurations:
          '[/**]':
            #allowedOrigins: * # 这种写法或者下面的都可以，*表示全部
            allowedOrigins:
              - "http://docs.spring.io"
            allowedMethods:
              - GET
eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
